### ISSUE TITLE
No se permiten agregar nuevos registros

### ISSUE THREAD

**Issue by GabrielMBulgarelli** [locompro/ci0128_23b_all_stars#204]
Hay problemas al agregar nuevos registros y no se logra enviar el formulario desde Submissions/Create y se permanece en la página.

Actualmente está vigente por lo menos en Develop. El error volvió a darse desde lo que parece ser el commit 
" 4f5deab78747ba3fa926fe02c56ce71cdc3dc407 ": 
Merge pull request #186 from locompro/bug/AS-306.

El último commit funcional sin el conflicto que encontré es el:
 " bcc1cb754c4c80470d68904b76f54045ef6c07c7 ":  
Merge pull request #187 from locompro/mainMergeIntoDevelop

**Comment by Antonio-Tresol** [comment]
Resuelto.
