### ISSUE TITLE
Al realizar una búsqueda desde la página de resultados, no realiza la búsqueda y se devuelve a la página principal

### ISSUE THREAD

**Issue by GabrielMBulgarelli** [locompro/ci0128_23b_all_stars#207]
Actualmente está vigente en Develop. Noto que al menos existe desde el commit " 493027187c59b280a43e223c6337862ef3f207fd ". En otras palabras, no se permite buscar dos veces seguidas. El problema lo ocasiona el AS-317

**Comment by joseph97svk** [comment]
Ya resuelto
